### PR TITLE
Proposed PEP8 fixes

### LINKED ISSUE #15: PEP8 issues
If you run `pep8` against the repo you'll find a number of issues

### PR DESCRIPTION
**Pull request by NdagiStanley**
### Changes proposed to this pull request
- Editions to the files to fix pep8 issues

@mbauman please review this pull request.

### CODE REVIEW

**Comment by gitgik** [comment]
Thanks for the PEP8 fixes. Can you be able to deploy this branch @NdagiStanley?

**Comment by NdagiStanley** [comment]
Doing that ASAP @gitgik

**Comment by NdagiStanley** [comment]
And there we have it @gitgik https://etp-api-pr16.herokuapp.com/

**Comment by gitgik** [comment]
LGMT 👍

**Pull request merged**
